name: "${APP_ID}_${APP_NAME}"

services:

  app:
    build: .
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    ports:
      - "10${APP_ID}:8000"
    container_name: "${APP_ID}_APP"

volumes:
  vendor_data:
